// Catálogo de permissões e perfis padrão — usado tanto no seed inicial
// (prisma/seed.ts, para a primeira empresa) como na criação de NOVAS
// empresas clientes (PlatformService), para nunca ficarem dessincronizados.
// Qualquer módulo/permissão novo adicionado ao sistema deve ser acrescentado
// aqui, e passa automaticamente a existir em todas as empresas — as já
// existentes recebem-no da próxima vez que o seed for corrido, as novas
// já nascem com ele.

export const PERMISSIONS: { module: string; action: string }[] = [
  { module: 'dashboard', action: 'view' },
  { module: 'users', action: 'view' },
  { module: 'users', action: 'create' },
  { module: 'users', action: 'update' },
  { module: 'users', action: 'delete' },
  { module: 'users', action: 'activate' },
  { module: 'users', action: 'suspend' },
  { module: 'users', action: 'block' },
  { module: 'users', action: 'restore' },
  { module: 'roles', action: 'view' },
  { module: 'roles', action: 'create' },
  { module: 'roles', action: 'update' },
  { module: 'roles', action: 'delete' },
  { module: 'permissions', action: 'view' },
  { module: 'audit', action: 'view' },
  { module: 'settings', action: 'view' },
  { module: 'settings', action: 'update' },
  { module: 'profile', action: 'view' },
  { module: 'profile', action: 'update' },
  { module: 'insured', action: 'view' },
  { module: 'insured', action: 'create' },
  { module: 'insured', action: 'update' },
  { module: 'insured', action: 'delete' },
  { module: 'insured', action: 'activate' },
  { module: 'insured', action: 'suspend' },
  { module: 'dependents', action: 'view' },
  { module: 'dependents', action: 'create' },
  { module: 'dependents', action: 'update' },
  { module: 'dependents', action: 'delete' },
  { module: 'companies', action: 'view' },
  { module: 'companies', action: 'create' },
  { module: 'companies', action: 'update' },
  { module: 'companies', action: 'delete' },
  { module: 'plans', action: 'view' },
  { module: 'plans', action: 'create' },
  { module: 'plans', action: 'update' },
  { module: 'plans', action: 'delete' },
  { module: 'plans', action: 'configure' },
  { module: 'policies', action: 'view' },
  { module: 'policies', action: 'create' },
  { module: 'policies', action: 'update' },
  { module: 'policies', action: 'delete' },
  { module: 'cards', action: 'view' },
  { module: 'cards', action: 'create' },
  { module: 'cards', action: 'update' },
  { module: 'providers', action: 'view' },
  { module: 'providers', action: 'create' },
  { module: 'providers', action: 'update' },
  { module: 'providers', action: 'delete' },
  { module: 'authorizations', action: 'view' },
  { module: 'authorizations', action: 'create' },
  { module: 'authorizations', action: 'approve' },
  { module: 'authorizations', action: 'reject' },
  { module: 'consultations', action: 'view' },
  { module: 'consultations', action: 'create' },
  { module: 'pharmacy', action: 'view' },
  { module: 'pharmacy', action: 'create' },
  { module: 'pharmacy', action: 'configure' },
  { module: 'laboratory', action: 'view' },
  { module: 'laboratory', action: 'create' },
  { module: 'laboratory', action: 'update' },
  { module: 'claims', action: 'view' },
  { module: 'claims', action: 'create' },
  { module: 'claims', action: 'approve' },
  { module: 'reimbursements', action: 'view' },
  { module: 'reimbursements', action: 'create' },
  { module: 'reimbursements', action: 'approve' },
  { module: 'billing', action: 'view' },
  { module: 'billing', action: 'create' },
  { module: 'billing', action: 'approve' },
  { module: 'payments', action: 'view' },
  { module: 'payments', action: 'create' },
  { module: 'payments', action: 'configure' },
  { module: 'reports', action: 'view' },
  { module: 'integrations', action: 'view' },
  { module: 'integrations', action: 'manage' },
  { module: 'agreements', action: 'view' },
  { module: 'agreements', action: 'create' },
  { module: 'agreements', action: 'update' },
  { module: 'agreements', action: 'delete' },
];

// "Superadministrador" é sempre um perfil de sistema (isSystem = true) e
// nunca pode ser eliminado pela aplicação.
export const ROLES: { name: string; code: string; isSystem: boolean }[] = [
  { name: 'Superadministrador', code: 'superadmin', isSystem: true },
  { name: 'Administrador', code: 'admin', isSystem: true },
  { name: 'Gestor de Seguros', code: 'insurance_manager', isSystem: false },
  { name: 'Operador de Cadastro', code: 'registration_operator', isSystem: false },
  { name: 'Gestor Financeiro', code: 'financial_manager', isSystem: false },
  { name: 'Auditor', code: 'auditor', isSystem: false },
  { name: 'Médico', code: 'doctor', isSystem: false },
  { name: 'Enfermeiro', code: 'nurse', isSystem: false },
  { name: 'Farmacêutico', code: 'pharmacist', isSystem: false },
  { name: 'Técnico de Laboratório', code: 'lab_technician', isSystem: false },
  { name: 'Recepcionista', code: 'receptionist', isSystem: false },
  { name: 'Gestor de Empresa', code: 'company_manager', isSystem: false },
  { name: 'Segurado', code: 'insured', isSystem: false },
  { name: 'Prestador', code: 'provider', isSystem: false },
  { name: 'Agente Comercial', code: 'sales_agent', isSystem: false },
  { name: 'Atendimento ao Cliente', code: 'customer_support', isSystem: false },
];
